
state_list = {
    'AL':'ALABAMA','AK':'ALASKA','AZ':'ARIZONA','AR':'ARKANSAS',
'AS':'American Samoa','CA':'CALIFORNIA','CO':'COLORADO','CT':'CONNETICUT',
'DE':'DELAWARE','DC':'DISTRICT OF COLUMBIA','FL':'FLORIDA',
'FM':'Federated States of Micronesia', 'GA':'GORGIA','GU':'Guam','HI':'HAWAII',
'ID':'IDAHO','IL':'ILLINOIS','IN':'INDIANA','IA':'IOWA','KS':'KANSAS',
'KY':'KENTUCKY','LA':'LOUISIANA','ME':'MAINE','MD':'MARYLAND',
'MA':'MASSACHUSETTS','MI':'MICHIGAN','MN':'MINNESOTA','MS':'MISSISSIPPI',
'MO':'MISSOURI','MT':'MONTANA','MH':'Marshall Islands', 'NE':'NEBRASKA',
'NV':'NEVADA', 'NH':'NEW HAMPSHIRE','NJ':'NEW JERSEY','NM':'NEW MEXICO',
'NY':'NEW YORK','NC':'NORTH CAROLINA', 'ND':'NORTH DAKOTA',
'MP':'Northern Mariana Islands','OH':'OHIO','OK':'OKLAHOMA','OR':'OREGON',
'PA':'PENNSYLVANIA','PW':'Palau','PR':'Puerto Rico','RI':'RHODE ISLAND',
'SC':'SOUTH CAROLINA','SD':'SOUTH DAKOTA','TN':'TENNESSEE','TX':'TEXAS',
'UM':'U.S. Minor Outlying Islands','UT':'UTAH','VT':'VERMONT','VA':'VIRGINIA',
'VI':'Virgin Islands of the U.S.','WA':'WASHINGTON','WV':'WEST VIRGINIA',
'WI':'WISCONSIN','WY':'WYOMING'

}